# Generated by Django 4.1 on 2022-09-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='craetedAt',
            new_name='createdAt',
        ),
    ]
